name: CD Pipeline
on:
    push:
      tags:
        - 'v*'
      branches:
        - main
    workflow_dispatch:
      inputs:
        rollback_version:
          description: "Tag of the version to rollback to (optional)"
          required: false
  
jobs:
    prod-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Get tag version
          id: get_version
          run: |
            if [ "${{ github.event.inputs.rollback_version }}" ]; then
              echo "Rollback version specified: ${{ github.event.inputs.rollback_version }}"
              echo "VERSION=${{ github.event.inputs.rollback_version }}" >> $GITHUB_ENV
            else
              echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            fi
  
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Build and push production image
          if: github.event_name == 'push'
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/note-app:latest
              ${{ secrets.DOCKER_USERNAME }}/note-app:${{ github.ref_name }}

        - name: Deploy to production server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/note-app:${{ github.ref_name }}
              docker stop prod-note-app || true
              docker rm prod-note-app || true
              docker run -d --name prod-note-app -p 1000:80 ${{ secrets.DOCKER_USERNAME }}/note-app:${{ github.ref_name }}
